### ISSUE TITLE
改为横屏需要修改哪些地方啊， 我发现了改了摄像头方向还是无法扫描到东西

### ISSUE THREAD

**Issue by tianshaokai** [xuyisheng/ZXingLib#10]

**Comment by cz000** [comment]
你可以搜索下 横屏改竖屏，好像总共改了四处，你逆着改回去，只改两处代码（有个是增添的if，不用改），最后，一定要在 配置文件中 加入 改为横屏的设置！（这个坑了我点儿时间）
